---
title: "Publications"
---

# Peer-reviewed publications

\* denotes co-first authors

## 2020

**Maciejewski MF**, Jiang C, Stuart YE, Bolnick DI. 2020. Microhabitat contributes to microgeographic divergence in threespine stickleback. Evolution. 74: 749-763. [Link](https://onlinelibrary.wiley.com/doi/abs/10.1111/evo.13942)

## 2019

**Maciejewski MF**, Hernandez CA, Bolnick DI. 2019. Investigating the association between armor coverage and parasite infection in an estuarine population of stickleback. Evol. Ecol. Res. 20: 69-82. [Link](http://www.evolutionary-ecology.com/issues/v20/n01/ffar3183.pdf)

**Maciejewski MF**, Meyer KS, Wheeler JD, Anderson EJ, Pittoors NC, Mullineaux LS. 2019. Helical swimming as an exploratory behavior in competent larvae of the eastern oyster (Crassostrea virginica). J. Exp. Mar. Biol. Ecol. 510: 86-94. [Link](https://www.sciencedirect.com/science/article/pii/S0022098118302879)

## Under review, under revision, or in prep

Hund AK\*, Fuess LE\*, Kenney ML, **Maciejewski MF**, Marini JM, Shim KC, Bolnick DI. Rapid evolution of parasite resistance via improved recognition and accelerated immune activation and deactivation. under revision, currently available on [bioRxiv](https://www.biorxiv.org/content/10.1101/2020.07.03.186569v1)

For the most up-to-date list of publications see my [Google Scholar](https://scholar.google.com/citations?user=EJt3cOkAAAAJ&hl=en) page
